### ISSUE TITLE
版本切换功能似乎并不完全

### ISSUE THREAD

**Issue by Ronneraz** [laomms/KmsTool#3]
测试环境：win11家庭版+微软surfacepro7Plus
使用工具切换为win11企业版与专业版后，直接win+r输入gpedit.msc报找不到文件。进入MMC后手动添加控制台发现无组策略管理模块
使用本工具切回家庭版，然后使用系统自带的激活面板更换密钥为网上找的企业版key之后，系统自动下载更新安装重启，此时gpedit.msc可用
感觉切换许可证更像是解锁那些在家庭版与专业版之间共同的组件，让一部分家庭版被限制的功能得以完全解锁（比如bitlocker，用工具切换后就变成完整版了而不是设备加密的阉割版）。但是并没有弥补原本专业版特有而家庭版没有的那部分组件，而这些组件通过微软自带的升级是可以在线下载获得的，单纯的导入证书并更换key并不能弥补这部分组件，希望工具能加入从微软服务器拉取组件这一步或者加个提醒，不然会误认为是玄学问题。

**Comment by laomms** [comment]
版本切换主要用于Office，Windows的切换只是切换了SKU，目的是为了激活用。这种情况下，如果想要相应版本的组件，得等windows更新中的大版本更新，升级后就有相关组件。

但是可以如你所说，可以直接通过离线输入目标版本升级密钥直接升级，比如Win10家庭版升级专业版，断网下在“开始-设置-更新和安全-激活”，在“更改产品密钥”中输入密钥VK7JG-NPHTM-C97JM-9MPGT-3V66T进行升级。
或者也可以通过Dism的方法：
查询可系统升级版本powershell命令：Dism /Online /Get-TargetEditions
在线升级系统：Dism /online /Set-Edition: <target edition name> /AcceptEula /ProductKey:<target edition key>
比如升级ServerStandard2019到ServerDatacenter2019命令：DISM.exe /online /Set-Edition:ServerDatacenter /ProductKey:NPTRB-CFYFD-DGFPG-DY9GJ-CPR8F /AcceptEula

这是微软给出的答案:
https://support.microsoft.com/en-us/help/12384/windows-10-upgrading-home-to-pro

另外，在mydigitallife上有通过更新UpgradeMatrix.xml的方法升级: 
https://forums.mydigitallife.net/threads/windows-editions-reconstruction-project.80939/

这些大部分比较耗时，不适合用在一个小工具里。
谢谢！

**Comment by Ronneraz** [comment]
好吧，dism切换sku的这个我之前自己也实验过，能对在线系统升级的只有winserver系列，包括各种评估版到正式版。普通的消费级win版本并不能通过dism直接在线升级，必须在部署完成后第一次启动前进入pe然后才能对离线系统进行升级。这一点很不方便。而且基于同样核心的sku单纯切换的话其实slmgr.vbs /ipk直接装载目标密钥就能切换，效果应该是一样的
另外如果不方便集成的话，可以在跨版本核心切换sku时进行提示一下，或者直接打开功能时弹窗提示一下，这样应该也方便用户理解操作的限制，让有需求的用户自行升级之后再激活，您觉得呢?
谢谢!

**Comment by laomms** [comment]
嗯，后续版本加入提示。
