### ISSUE TITLE
2.5.2问题

### ISSUE THREAD

**Issue by ljwbh** [laomms/KmsTool#7]
今天下载2.5.2后使用，lsct2021  1944.2673  可以激活，但激活后无法查看系统信息（显示错误），并点击后，无法显示重启和关机。同样系统，用2.2版本可以激活并没有任何问题出现

**Comment by ljwbh** [comment]
![11](https://user-images.githubusercontent.com/41594793/221391139-12af4455-8760-4e14-9358-a504c12971ba.gif)
这是错误动画

**Comment by ljwbh** [comment]
这是2.2激活的动画，无问题
![12](https://user-images.githubusercontent.com/41594793/221391205-ef669d41-36cc-437a-be2b-a6431f9fce5c.gif)

**Comment by laomms** [comment]
感谢反馈，已更新。

**Comment by ljwbh** [comment]
2.5.3   运行到正在获取数字信息时，程序就自动关了
![11](https://user-images.githubusercontent.com/41594793/221738751-fc870395-e5eb-4559-ac46-45312bcd0d0e.gif)
